version = 0.1
[default.deploy.parameters]
stack_name = "dav-backend-ws-luciana"
resolve_s3 = true
s3_prefix = "dav-backend-ws-luciana"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
